// SUNPLUS  S+core IDE generated include file.
#ifndef HYPERSCAN_RESOURCE_H__26308_13931__INCLUDED_
#define HYPERSCAN_RESOURCE_H__26308_13931__INCLUDED_

extern unsigned char* _binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_System_HyperScan_examples_CD_USBLoaderCD_cdusbldr_bin_start;
#define RES_CDUSBLDR_BIN (unsigned char*)&_binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_System_HyperScan_examples_CD_USBLoaderCD_cdusbldr_bin_start
extern unsigned char* _binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_System_HyperScan_examples_CD_USBLoaderCD_cdusbldr_bin_end;
#define RES_CDUSBLDR_BIN_END (unsigned char*)&_binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_System_HyperScan_examples_CD_USBLoaderCD_cdusbldr_bin_end


#endif //HYPERSCAN_RESOURCE_H__26308_13931__INCLUDED_
