// SUNPLUS  S+core IDE generated include file.
#ifndef HYPERSCAN_RESOURCE_H__10555_21425__INCLUDED_
#define HYPERSCAN_RESOURCE_H__10555_21425__INCLUDED_

extern unsigned char* _binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_hyperscan_examples_USBLoader_Resource_Brown_Eyes_8k_test_wav_mp3_start;
#define RES_BROWN_EYES_8K_TEST_WAV_MP3 (unsigned char*)&_binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_hyperscan_examples_USBLoader_Resource_Brown_Eyes_8k_test_wav_mp3_start
extern unsigned char* _binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_hyperscan_examples_USBLoader_Resource_Brown_Eyes_8k_test_wav_mp3_end;
#define RES_BROWN_EYES_8K_TEST_WAV_MP3_END (unsigned char*)&_binary_C__Users_ppcas_OneDrive_Documents_GitHub_HyperScan_SPG29x_SDK_hyperscan_examples_USBLoader_Resource_Brown_Eyes_8k_test_wav_mp3_end


#endif //HYPERSCAN_RESOURCE_H__10555_21425__INCLUDED_
